Задание 5 спринта
ed-mechanics/go-first-floor-sprint-five pull request #1
Opened 2024-02-25 23:08 UTC by ed-mechanics

2024-02-26 04:24 UTC, just-musha requested changes
Привет! Отличная работа. Давай добавим проверки на 0 перед делением на переменную и поправим ReadData. В остальном все хорошо

2024-02-26 04:24 UTC, just-musha commented on main.go
> +	return t.distance() / t.Duration.Hours()
Что, если Duration = 0 ? Давай добавим проверку как в 4 спринте.
Здесь и дальше по коду, где есть деление на переменную

2024-02-26 04:24 UTC, just-musha commented on main.go
> +	return ((CaloriesMeanSpeedMultiplier*speed + CaloriesMeanSpeedShift) * r.Weight / MInKm * r.Duration.Hours() * MinInHours)
Внешние скобки можно убрать, они ни на что не влияют

2024-02-26 04:24 UTC, just-musha commented on main.go
> +	return ((speed + SwimmingCaloriesMeanSpeedShift) * SwimmingCaloriesWeightMultiplier * s.Weight * s.Duration.Hours())
И здесь

2024-02-26 04:24 UTC, just-musha commented on main.go
> +		Calories:     s.Calories(),
По заданию предполагается что калории будут проставлены в методе ReadData. Давай так и сделаем

2024-02-28 09:28 UTC, ed-mechanics commented
Лично мне было удобнее, чтобы подготовка сообщения была вынесена, но раз надо - значит надо :D

2024-02-28 10:49 UTC, just-musha approved these changes
Так, а можно же было оставить fmt.Sprint(info). Это правда. Комментарий в ревью оставила. Никакого "надо" нет, все обсуждаемо. Здорово что написал!

Принято.

2024-02-28 10:49 UTC, just-musha commented on main.go
> +	return fmt.Sprintf("Тип тренировки: %s\nДлительность: %v мин\nДистанция: %.2f км.\nСр. скорость: %.2f км/ч\nПотрачено ккал: %.2f\n",
Так, а можно же было оставить `fmt.Sprint(info)` ! 
Возможно это было недопонимание, мой посыл был в том, чтобы добавить  вот это: `info.Calories = calories`
Что ты и сделал :+1: 

Никакого "надо" нет, все обсуждаемо. Здорово что написал!

2024-02-28 10:51 UTC, ed-mechanics commented on main.go
> +	return fmt.Sprintf("Тип тренировки: %s\nДлительность: %v мин\nДистанция: %.2f км.\nСр. скорость: %.2f км/ч\nПотрачено ккал: %.2f\n",
Понял, азахваха, окей, произошел мисандерстендинг. Но я рад, что вам понравилось)

2024-02-29 03:23 UTC, merged